force-app/main/default/objects/System_Event__c/System_Event__c.object-meta.xml
<CustomObject>
    <label>System Event</label>
    <nameField>
        <displayFormat>EVENT-{000000}</displayFormat>
        <label>Event ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/System_Event__c/fields/Complete_Trace_String__c.field-meta.xml
<CustomField>
    <fullName>Complete_Trace_String__c</fullName>
    <label>Complete Trace String</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/System_Event__c/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <label>Component Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Event__c/fields/Component_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Type__c</fullName>
    <label>Component Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex Class</fullName>
            </value>
            <value>
                <fullName>Apex Trigger</fullName>
            </value>
            <value>
                <fullName>Lighting Flow</fullName>
            </value>
            <value>
                <fullName>Platform Event</fullName>
            </value>
            <value>
                <fullName>Batch Apex</fullName>
            </value>
            <value>
                <fullName>Queueable Apex</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/System_Event__c/fields/Exception_Type__c.field-meta.xml
<CustomField>
    <fullName>Exception_Type__c</fullName>
    <label>Exception Type</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/System_Event__c/fields/Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Line_Number__c</fullName>
    <label>Line Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/System_Event__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>System_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Logger.cls
public class Logger {

    public static System_Event__c logError(String title){
        System_Event__c event = new System_Event__c();
        event.Complete_Trace_String__c = '';
        event.Title__c = title; // Identifer
        event.Component_Name__c = '';
        event.Component_Type__c = '';
        event.Exception_Type__c = '';
        event.Line_Number__c = '';
        event.Message__c = '';
        event.User__c = null;
        return event;
    }
    
}